development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: myapp_development

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: myapp_production

test:
  adapter: async
