development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: draw_development

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: draw_production

test:
  adapter: async
